In [1]:
import numpy as np

In [2]:
a=np.array([2,3,4])

In [3]:
print(a)

[2 3 4]


In [4]:
sam=np.array([(1,2,3),(2,3,4)])

In [5]:
print(sam)

[[1 2 3]
 [2 3 4]]


In [6]:
sam1=np.transpose(sam)

In [7]:
print(sam1)

[[1 2]
 [2 3]
 [3 4]]


In [8]:
sam1.ravel()

array([1, 2, 2, 3, 3, 4])

In [9]:
sam1.reshape(3,2)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [14]:
sam2=np.zeros((3,1))

In [15]:
print(sam2)

[[0.]
 [0.]
 [0.]]


In [16]:
np.append(sam2,sam1)

array([0., 0., 0., 1., 2., 2., 3., 3., 4.])

In [17]:
np.insert(sam1,2,5)

array([1, 2, 5, 2, 3, 3, 4])

In [18]:
np.delete(sam1,2)

array([1, 2, 3, 3, 4])

In [19]:
np.random.random((3,2))

array([[0.74986246, 0.39413362],
       [0.34096506, 0.94310563],
       [0.85625215, 0.20397727]])